### ISSUE TITLE
Generalize text

### ISSUE THREAD

**Issue by miguel-mzbi** [fornesarturo/its-not-raining#28]
Let's store the text to draw in the level's JSON.
And it would be nice if the end-of-the-level text showed for more than 1 sprite.

**Comment by fornesarturo** [comment]
Now it's done.

**Comment by fornesarturo** [comment]
:octocat:

**Comment by miguel-mzbi** [comment]
Now the end-of-the-game-text acts as a loading screen.

:octocat: 🐙
