### ISSUE TITLE
Development aid for level creation.

### ISSUE THREAD

**Issue by fornesarturo** [fornesarturo/its-not-raining#45]
🏗

**Comment by miguel-mzbi** [comment]
New branch for this issue:
[level-aid](https://github.com/fornesarturo/its-not-raining/tree/level-aid)

**Comment by miguel-mzbi** [comment]
[](url)

**Comment by miguel-mzbi** [comment]
Everything it's working now.
I will create a keyboard shortcut during gameplay to force reloading the level, to make testing the level easier. (It won't be necessary to refresh the page)

**Comment by miguel-mzbi** [comment]
Done
[Pull request](https://github.com/fornesarturo/its-not-raining/pull/51)
